### ISSUE TITLE
Interpreting the parameter file

### ISSUE THREAD

**Issue by vertesy** [Nik-Tavakolian/Shepherd#1]
Hi Nik,

thanks for this great package! Could you please help me with interpreting the parameter file?

After reading the pickle, I get the following:
```py
[1, 14, 10, 8, 0.10668884789991079, 0.14772464475406577, -4, 33.97225039728807, 124468, 5]
```

What value corresponds to what? 
Assuming the the order as listed in your readme.md, plus ignoring the first value, it would be:
(and it doesn't seem right)

val | arg | desc
-- | -- | --
14 | -l | The correct barcode length.
10 | -f | The input file with a sequence and a sequence count in each row, separated by whitespace. Currently this is the only input file format supported by Shepherd. Only sequences in the file with lengths l (correct barcode length), l + 1 (single insertion errors) and l - 1 (single deletion errors) will be processed by Shepherd.
8 | -e | n estimate of the substitution error rate of the sequencing protocol used to generate the input data. This is a floating point number, e.g. 0.01 if the estimated error rate is 1%. If not provided this parameter is automatically determined based on the input data.
0.1066888479 | -eps | The maximum Hamming distance considered for merging two sequencing into the same cluster. If not provided this parameter is automatically determined based on the input data.
0.1477246448 | -k | The substring length used to divide the sequences into partitions. If not provided this parameter is automatically determined based on the input data.
-4 | -tau | A distance threshold for frequency 1 sequences that determines if they should be merged with another sequence. If a frequency 1 sequence has Hamming distance less than or equal to this threshold to a candidate sequence it will be merged. If not provided this parameter is automatically determined based on the input data.
33.9722504 | -ft | A frequency threshold for defining true barcodes. Any sequence with a frequency higher than this threshold is defined as a true barcode. If not provided this parameter is automatically determined based on the input data.
124468 | -bft | he threshold for log Bayes factor. The default value is -4.
5 | -Nh | Number of sequences used for estimation of the substitution error rate. The default value is min(number of sequences, 500).

**Comment by Nik-Tavakolian** [comment]
Hi Abel,

Glad to hear that you like the package!

The purpose of the parameter pickle file is actually to save the parameters for later use in the multiple time point script to avoid estimating some of the parameters again. Some of the parameters in the file are only used internally by the program and so they do not appear in the list of arguments in the readme. All parameters that are essential for the error correction are displayed in the command line when the shepherd_t0.py script is executed.

With that said the pickle file is ordered in the following way:

[k, l, Number of Partitions, eps, Internal parameter, e, bft, Internal parameter, ft, tau]

Looking at the parameters you obtain what stands out to me is the error rate of around 15% which is also used to estimate the other parameters. This seems exceedingly high to me so I would be curious to know what type of the data you are working with.

**Comment by vertesy** [comment]
Thanks Nik, clear now!

I wrote an R function to (a) convert the pickle to .TSV and save it, or (b) read in a particular number (by providing the index value to `extract_one_value`, e.g. 6 will return the _An estimate of the substitution rate_) or the whole param list as table with descriptions. 

```r
ww.Shepherd.ReadPicke <- function(filename, view_it = F, reorder = T, extract_one_value = F, write_it = !extract_one_value) {
  
  Values = unlist(reticulate::py_load_object(filename))
  if (length(Values) == 10) {
    (ValuesX = as.character(signif(Values, digits = 3)))
    asterisk = '*If not provided this parameter is automatically determined based on the input data.'
    dfx = structure(list(Argument = c("k", "l", "", "eps", "", "e", "bft", "", "ft", "tau")
                         , Description = c("The substring length used to divide the sequences into partitions.*"
                                           , "The correct barcode length.", "Number of Partitions"
                                           , "The maximum Hamming distance considered for merging two sequencing into the same cluster.*"
                                           , "Internal parameter"
                                           , "An estimate of the substitution error rate of the sequencing protocol used to generate the input data. This is a floating point number, e.g. 0.01 if the estimated error rate is 1%.*"
                                           , "The threshold for log Bayes factor. The default value is -4."
                                           , "Internal parameter"
                                           , "A frequency threshold for defining true barcodes. Any sequence with a frequency higher than this threshold is defined as a true barcode.*"
                                           , "A distance threshold for frequency 1 sequences that determines if they should be merged with another sequence. If a frequency 1 sequence has Hamming distance less than or equal to this threshold to a candidate sequence it will be merged.*"
                         )), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -10L))
    
    ValuesX[6] = paste(100 * signif(Values[6], 3), "%", sep = ' ')
    
    dfx = cbind(ValuesX, dfx)
    
    if (reorder) dfx = dfx[ c(6, 4, 1, 2, 3, 7, 9, 10, 5, 8),]
    print(cbind(dfx[,1:2], substr(dfx[,3], start = 1, stop = 40)))
    print(asterisk)

    if (view_it) View(dfx)
    if (write_it) write_delim(x = dfx, delim = '\t', file = paste0(filename, '.tsv'))
    if (extract_one_value) Values[extract_one_value] else dfx # If to return only one value that you are interested in.
  } else {
    print("ERROR: length(Values) is not 10!"); print("ERROR: length(Values) is not 10!"); print("ERROR: length(Values) is not 10!")
    VAL = as.data.frame(Values)
    write_delim(x = VAL, delim = '\t', file = paste0(filename, 'ERROR.tsv'))
    if (extract_one_value) NaN else VAL 
  }

}
```

The core functionality is
```r
reticulate::py_load_object(filename)
```
### Example output
(saved as .tsv)

ValuesX | Argument | Description
-- | -- | --
0.73% | e | An estimate of the substitution error rate of the sequencing protocol   used to generate the input data. This is a floating point number, e.g. 0.01   if the estimated error rate is 1%.*
3 | eps | The maximum Hamming distance considered for merging two sequencing into   the same cluster.*
3 | k | The substring length used to divide the sequences into partitions.*
14 | l | The correct barcode length.
5 |   | Number of Partitions
-4 | bft | The threshold for log Bayes factor. The default value is -4.
84 | ft | A frequency threshold for defining true barcodes. Any sequence with a   frequency higher than this threshold is defined as a true barcode.*
2 | tau | A distance threshold for frequency 1 sequences that determines if they   should be merged with another sequence. If a frequency 1 sequence has Hamming   distance less than or equal to this threshold to a candidate sequence it will   be merged.*
0.903 |   | Internal parameter
29.1 |   | Internal parameter



After checking multiple samples, the error rate varies a lot across samples we tried. I followed up in email, as it leads out of this thread. 

Thank you! 
Abel
